[2025-06-08T18:54:53.130+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_daily_data_dag.exploitation_delta_tables_task manual__2025-06-08T18:48:49.417791+00:00 [queued]>
[2025-06-08T18:54:53.141+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_daily_data_dag.exploitation_delta_tables_task manual__2025-06-08T18:48:49.417791+00:00 [queued]>
[2025-06-08T18:54:53.142+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-08T18:54:53.161+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): exploitation_delta_tables_task> on 2025-06-08 18:48:49.417791+00:00
[2025-06-08T18:54:53.165+0000] {standard_task_runner.py:60} INFO - Started process 1848 to run task
[2025-06-08T18:54:53.170+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'update_daily_data_dag', 'exploitation_delta_tables_task', 'manual__2025-06-08T18:48:49.417791+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/scheduled_task.py', '--cfg-path', '/tmp/tmpc8ej0wtu']
[2025-06-08T18:54:53.173+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask exploitation_delta_tables_task
[2025-06-08T18:54:53.201+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-08T18:54:53.239+0000] {task_command.py:423} INFO - Running <TaskInstance: update_daily_data_dag.exploitation_delta_tables_task manual__2025-06-08T18:48:49.417791+00:00 [running]> on host 7d0db884b06d
[2025-06-08T18:54:53.598+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_daily_data_dag' AIRFLOW_CTX_TASK_ID='exploitation_delta_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T18:48:49.417791+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T18:48:49.417791+00:00'
[2025-06-08T18:56:00.759+0000] {logging_mixin.py:188} INFO - Error: Delta table `../Project_1/Data Management/Trusted Zone/imbd/imbd_name_basics` doesn't exist.
[2025-06-08T18:56:00.760+0000] {python.py:201} INFO - Done. Returned value was: False
[2025-06-08T18:56:00.974+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=update_daily_data_dag, task_id=exploitation_delta_tables_task, execution_date=20250608T184849, start_date=20250608T185453, end_date=20250608T185600
[2025-06-08T18:56:01.183+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T18:56:01.193+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
