[2025-06-07T13:36:39.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_daily_data_dag.exploitation_delta_tables_task scheduled__2025-06-05T23:30:00+00:00 [queued]>
[2025-06-07T13:36:39.338+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_daily_data_dag.exploitation_delta_tables_task scheduled__2025-06-05T23:30:00+00:00 [queued]>
[2025-06-07T13:36:39.339+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-07T13:36:39.419+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): exploitation_delta_tables_task> on 2025-06-05 23:30:00+00:00
[2025-06-07T13:36:39.454+0000] {standard_task_runner.py:60} INFO - Started process 1826 to run task
[2025-06-07T13:36:39.458+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'update_daily_data_dag', 'exploitation_delta_tables_task', 'scheduled__2025-06-05T23:30:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/scheduled_task.py', '--cfg-path', '/tmp/tmpl_vk88w9']
[2025-06-07T13:36:39.463+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask exploitation_delta_tables_task
[2025-06-07T13:36:39.515+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-07T13:36:39.595+0000] {task_command.py:423} INFO - Running <TaskInstance: update_daily_data_dag.exploitation_delta_tables_task scheduled__2025-06-05T23:30:00+00:00 [running]> on host 9eafd80829be
[2025-06-07T13:36:39.732+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_daily_data_dag' AIRFLOW_CTX_TASK_ID='exploitation_delta_tables_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-05T23:30:00+00:00'
[2025-06-07T13:36:47.748+0000] {python.py:201} INFO - Done. Returned value was: False
[2025-06-07T13:36:47.836+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=update_daily_data_dag, task_id=exploitation_delta_tables_task, execution_date=20250605T233000, start_date=20250607T133639, end_date=20250607T133647
[2025-06-07T13:36:47.906+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-07T13:36:47.927+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
